"""changed the priamry key of the review to ID

Revision ID: 04fe08750ee8
Revises: 52a1ff3d029d
Create Date: 2024-01-15 23:47:49.925876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04fe08750ee8'
down_revision: Union[str, None] = '52a1ff3d029d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('book_id', sa.BIGINT(), nullable=False))
    op.drop_constraint('reviews_book_isbn_fkey', 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reviews', 'book_isbn')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('book_isbn', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key('reviews_book_isbn_fkey', 'reviews', 'books', ['book_isbn'], ['isbn'], ondelete='CASCADE')
    op.drop_column('reviews', 'book_id')
    # ### end Alembic commands ###
