"""changed the priamry key of the like to ID

Revision ID: 52a1ff3d029d
Revises: 19b9020f42e1
Create Date: 2024-01-15 23:40:44.595949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a1ff3d029d'
down_revision: Union[str, None] = '19b9020f42e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('book_id', sa.BIGINT(), nullable=False))
    op.drop_constraint('likes_book_isbn_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.drop_column('likes', 'book_isbn')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('book_isbn', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_book_isbn_fkey', 'likes', 'books', ['book_isbn'], ['isbn'], ondelete='CASCADE')
    op.drop_column('likes', 'book_id')
    # ### end Alembic commands ###
