"""edited review tables

Revision ID: 575be9fcb5b4
Revises: ddf52bc6b3a1
Create Date: 2024-01-05 23:16:34.339708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575be9fcb5b4'
down_revision: Union[str, None] = 'ddf52bc6b3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
