"""added reason_for_deletion in the users table

Revision ID: b9b53468cba6
Revises: 6749e924d682
Create Date: 2024-01-04 21:56:10.742084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b53468cba6'
down_revision: Union[str, None] = '6749e924d682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reason_for_deletion', sa.String(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reason_for_deletion')
    # ### end Alembic commands ###
